/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BetManager } from "./BetManager";
export type { ERC20 } from "./ERC20";
export type { Multicall } from "./Multicall";
export * as factories from "./factories";
export { BetManager__factory } from "./factories/BetManager__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
