/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BetManager__factory } from "./BetManager__factory";
export { ERC20__factory } from "./ERC20__factory";
export { Multicall__factory } from "./Multicall__factory";
